env: "development"  # или "production", "staging"
CONFIG_PATH: "configs/config.yaml"
server:
  port: 8082
  host: "localhost"
  timeout: 4s
  idle_timeout: 30s


database:
  type: "postgres"
  host: "localhost"
  port: 8081
  user: postgres
  password: "1234"

logging:
  level: info
  format: json  # или "text"
  output: stdout
